### ISSUE TITLE
WiFi SSID

### ISSUE THREAD

**Issue by refleckto** [Nghi-NV/wifi-info#2]
The network name is always null
All permissions have been granted. I tried it on my smartphone and it didn’t work.

**Comment by Nghi-NV** [comment]
> The network name is always null All permissions have been granted. I tried it on my smartphone and it didn’t work.

You must enable Wifi-Entitlement by going to Target->Signing & Capabilities and adding Access WiFi Information or adding com.apple.developer.networking.wifi-info directly to your entitlements file
